import { e, layout } from './views.js';
import { findAutomation } from './catalog.js';
import { DAY } from './analytics.js';

const num = n => Number(n || 0).toLocaleString('en-US', { maximumFractionDigits: 1 });
const percent = (n, d) => d ? `${num(100 * n / d)}%` : '—';
const usd = n => `$${(Number(n || 0) / 1e6).toFixed(2)}`;
const day = ms => new Date(ms).toLocaleDateString('en-US', { timeZone: 'UTC', month: 'short', day: 'numeric', year: 'numeric' });
const duration = ms => ms == null ? '—' : ms < 1000 ? `${num(ms)} ms` : ms < 60000 ? `${num(ms / 1000)} s` : ms < 3600000 ? `${num(ms / 60000)} min` : `${num(ms / 3600000)} hr`;
const change = (n, prev, covered = true) => !covered ? 'Comparison collecting history' : !prev ? (n ? 'No prior-period baseline' : 'No change from prior period') : `${n >= prev ? '+' : '−'}${num(Math.abs(n - prev) / prev * 100)}% vs prior period`;
const metric = (label, value, note, detail, extra = '') => `<article class="metric ${extra}"><h2>${label}</h2><strong>${value}</strong><p>${note}</p><small>${detail}</small></article>`;
const rateCell = (n, d) => `<td class="num"><strong>${percent(n, d)}</strong><small>${num(n)} / ${num(d)} eligible</small></td>`;
const emptyRow = (span, text) => `<tr><td colspan="${span}" class="analytics-empty">${text}</td></tr>`;

function activityChart(data) {
  const width = 1000, height = 180, bottom = 205;
  const max = Math.max(1, ...data.daily.map(d => d.runs + d.failures));
  const step = (width - 56) / data.days;
  const bars = data.daily.map((d, i) => {
    const x = 42 + i * step, bw = Math.max(1, step - 3);
    const h = d.runs / max * height, fh = d.failures / max * height;
    const label = `${day(d.time)}: ${num(d.runs)} completed, ${num(d.failures)} failed, ${num(d.active)} active users${d.covered ? '' : '; incomplete coverage'}`;
    return `<g><title>${e(label)}</title>${!d.covered ? `<rect class="chart-untracked" x="${x}" y="25" width="${bw}" height="180"/>` : ''}<rect class="chart-success" x="${x}" y="${bottom - h}" width="${bw}" height="${h}" rx="2"/><rect class="chart-failure" x="${x}" y="${bottom - h - fh}" width="${bw}" height="${fh}" rx="2"/></g>`;
  }).join('');
  return `<svg class="activity-chart" viewBox="0 0 1000 245" role="img" aria-labelledby="chart-title chart-description">
    <title id="chart-title">Daily completed and failed requests</title><desc id="chart-description">${data.days} complete UTC days. ${num(data.current.runs)} completed requests. Hatched columns have incomplete measurement. Exact daily values are in the table below.</desc>
    <defs><pattern id="untracked" width="8" height="8" patternUnits="userSpaceOnUse"><path d="M0 8L8 0" class="chart-hatch"/></pattern></defs>
    ${[0, .5, 1].map(n => `<line class="chart-grid" x1="42" y1="${bottom - n * height}" x2="990" y2="${bottom - n * height}"/><text x="30" y="${bottom - n * height + 4}" text-anchor="end">${num(max * n)}</text>`).join('')}
    ${bars}<text x="42" y="234">${e(day(data.start))}</text><text x="990" y="234" text-anchor="end">${e(day(data.end - DAY))}</text></svg>`;
}

export function admin({ user, data: d }) {
  const { current: c, previous: p, weekly: w, totals: t, money: m } = d;
  const blocked = d.failures.find(f => f.status === 402)?.users || 0;
  const statusLabels = { 400: 'Input rejected', 402: 'Insufficient credit', 404: 'Unknown shortcut', 413: 'Input too large', 422: 'Unusable output', 429: 'Rate limited', 500: 'Server error', 502: 'Provider error', 503: 'Service unavailable' };
  const sourceNames = { 'iphone-app': 'iPhone app key', 'shortcut-key': 'Shortcut key', api: 'Custom API key', unknown: 'Unknown source' };
  const featureName = slug => findAutomation(slug)?.name || ({ 'custom-api': 'Custom API', 'raw-api': 'Raw model API', 'retired-shortcut': 'Unknown shortcut' })[slug] || slug || 'Unknown';
  const fRows = d.features.map(f => `<tr><td><strong>${e(featureName(f.slug))}</strong><small>${e(findAutomation(f.slug)?.category || 'API')}</small></td><td class="num">${num(f.users)}<small>${percent(f.users, c.active)} of active users</small></td><td class="num">${num(f.runs)}</td>${rateCell(f.repeat_users, f.users)}<td class="num">${percent(f.runs, f.attempts)}<small>${num(f.attempts - f.runs)} failed / ${num(f.attempts)} requests</small></td><td class="num">${num(f.credit_blocks)}</td><td class="num">${duration(f.p95_ms)}</td></tr>`).join('');
  const cohortRows = d.cohorts.map(x => `<tr><td>${e(x.week)}<small>${num(x.signups)} signups</small></td>${rateCell(x.activated7, x.eligible7)}${rateCell(x.retained14, x.eligible14)}${rateCell(x.retained35, x.eligible35)}${rateCell(x.paid30, x.eligible30)}</tr>`).join('');
  return layout({ title: 'Product analytics', user, active: '/admin', stylesheet: '/admin.css', body: `
<div class="analytics wrap">
  <header class="analytics-heading"><div><p class="analytics-eyebrow">Advanced Automations / Admin</p><h1>Are we becoming a habit?</h1><p>Track the path from a first useful result to a reason to come back.</p></div><a class="btn btn-soft btn-sm" href="/admin/export?days=${d.days}">Export data ↗</a></header>
  <div class="analytics-toolbar"><nav aria-label="Reporting period">${[7, 30, 90].map(n => `<a href="/admin?days=${n}"${d.days === n ? ' aria-current="page"' : ''}>${n} days</a>`).join('')}</nav><span>${day(d.start)} – ${day(d.end - DAY)} · complete UTC days</span><a href="/admin?days=${d.days}">Refresh ↻</a></div>
  <aside class="coverage-note"><span class="coverage-icon" aria-hidden="true">◷</span><div><strong>${d.coverage.period ? 'Measured activity' : 'New measurement window'}</strong><p>Request tracking began ${day(d.trackingSince)}. ${d.coverage.period ? 'Selected days are covered.' : 'Earlier activity is unknown; counts below are observed activity only.'} Signup cohorts include only accounts created after tracking began. Billing history remains available.</p></div></aside>

  <section class="analytics-kpis" aria-label="Core product metrics">
    ${metric('Weekly repeat users', num(w.repeat_users), 'Successful runs on 2+ distinct days in the last 7 complete days.', `${num(w.active)} weekly active · ${change(w.repeat_users, w.previous_repeat_users, d.coverage.weekly)}`, 'north-star')}
    ${metric('7-day activation', percent(t.activated7, t.eligible7), 'New accounts reaching a first successful run within 7 days.', `${num(t.activated7)} / ${num(t.eligible7)} mature signups · ${num(t.signups - t.eligible7)} still maturing`)}
    ${metric('Week 1 retention', percent(t.retained14, t.eligible14), 'Activated newcomers who return on days 7–13 after signup.', `${num(t.retained14)} / ${num(t.eligible14)} eligible activated accounts`)}
    ${metric('Run success rate', percent(c.runs, c.attempts), 'Authenticated requests returning a usable API result.', `${num(c.runs)} / ${num(c.attempts)} requests · includes credit and input failures`)}
  </section>

  <section class="analytics-actions" aria-labelledby="actions-title"><div class="section-heading"><div><p class="analytics-eyebrow">Where to focus</p><h2 id="actions-title">Turn signals into a next step.</h2></div><span>Observed counts, not targets</span></div><div class="action-grid">
    <a href="#activation"><b>${num(t.eligible7 - t.activated7)}</b><strong>Missed first value</strong><p>Mature signups without a successful run in week one. Review setup and starter credit.</p></a>
    <a href="#quality"><b>${num(blocked)}</b><strong>Credit-blocked users</strong><p>People who hit insufficient credit. Check top-up friction and required reservations.</p></a>
    <a href="#engagement"><b>${d.coverage.weekly ? num(w.lapsed) : '—'}</b><strong>Went quiet this week</strong><p>${d.coverage.weekly ? 'Active in the previous week, absent this week. Investigate their last useful workflow.' : 'Needs 14 complete days of request history before interpreting lapses.'}</p></a>
  </div></section>

  <section class="analytics-panel" id="engagement"><div class="section-heading"><div><p class="analytics-eyebrow">Engagement</p><h2>Useful moments, over time</h2><p>One completed request = one result delivered. Audio pipelines count once.</p></div><div class="chart-legend"><span class="legend-success">Completed</span><span class="legend-failure">Failed</span><span>▧ Incomplete history</span></div></div>
    <div class="engagement-stats"><div><strong>${num(c.active)}</strong><span>Active users</span><small>${change(c.active, p.active, d.coverage.comparison)}</small></div><div><strong>${num(c.runs)}</strong><span>Completed runs</span><small>${change(c.runs, p.runs, d.coverage.comparison)}</small></div><div><strong>${c.active ? num(c.runs / c.active) : '—'}</strong><span>Runs per active user</span><small>${c.active ? num(c.active_days / c.active) : '—'} average active days</small></div><div><strong>${percent(c.repeat_users, c.active)}</strong><span>Repeat-use rate</span><small>${num(c.repeat_users)} / ${num(c.active)} on 2+ days</small></div></div>
    ${activityChart(d)}
    <details class="analytics-details"><summary>Daily values and measurement coverage</summary><div class="analytics-scroll"><table class="table"><caption>Complete UTC days in the selected period</caption><thead><tr><th>Date</th><th>Coverage</th><th class="num">Active users</th><th class="num">Completed</th><th class="num">Failed</th></tr></thead><tbody>${d.daily.map(x => `<tr><td>${day(x.time)}</td><td>${x.covered ? 'Complete' : 'Partial / untracked'}</td><td class="num">${num(x.active)}</td><td class="num">${num(x.runs)}</td><td class="num">${num(x.failures)}</td></tr>`).join('')}</tbody></table></div></details>
  </section>

  <section class="analytics-panel" id="activation"><div class="section-heading"><div><p class="analytics-eyebrow">Activation → retention → payment</p><h2>Does first value turn into lasting value?</h2><p>Signup weeks within the selected period. Each rate shows its own mature denominator.</p></div></div>
    <div class="cohort-summary"><span><b>${num(m.signups)}</b> total signups in period</span><span><b>${t.activated7 ? duration(t.activation_ms / t.activated7) : '—'}</b> mean time to first value among 7-day activators</span><span><b>${d.coverage.weekly ? percent(w.retained, w.previous_active) : '—'}</b> previous-week users returning this week (${num(w.retained)} / ${num(w.previous_active)})</span></div>
    <div class="analytics-scroll"><table class="table cohort-table"><caption>Rates use signup age, not calendar-week age</caption><thead><tr><th>Signup week (UTC)</th><th class="num">Activated in 7d</th><th class="num">Week 1 return</th><th class="num">Week 4 return</th><th class="num">Paid in 30d</th></tr></thead><tbody>${cohortRows || emptyRow(5, 'No eligible signup cohorts yet. New cohorts appear as accounts join; retention requires time to mature.')}</tbody></table></div>
    <p class="analytics-footnote">Activation: signup age ≥7 days. Retention: activated within 7 days, then a success on days 7–13 or 28–34; eligible only at ages ≥14 or ≥35 days. Payment: first production purchase within 30 days, eligible at age ≥30 days. “—” means no eligible accounts. Small samples are directional.</p>
  </section>

  <section class="analytics-panel" id="features"><div class="section-heading"><div><p class="analytics-eyebrow">Product decisions</p><h2>Which workflows deserve investment?</h2><p>Look for reach, repeat use, and reliable results together. Users may use multiple workflows.</p></div></div><div class="analytics-scroll"><table class="table feature-table"><caption>Ranked by people receiving successful results</caption><thead><tr><th>Workflow</th><th class="num">Active users</th><th class="num">Runs</th><th class="num">Repeat on 2+ days</th><th class="num">Success</th><th class="num">Credit blocks</th><th class="num">P95 latency</th></tr></thead><tbody>${fRows || emptyRow(7, 'No authenticated requests recorded in this period.')}</tbody></table></div><p class="analytics-footnote">P95 is the 95th percentile of end-to-end server duration for successful requests, excluding analytics persistence. A successful API response is a proxy for value; output satisfaction and time saved are not measured.</p></section>

  <div class="analytics-columns"><section class="analytics-panel" id="quality"><div class="section-heading"><div><p class="analytics-eyebrow">Remove friction</p><h2>What stopped a result?</h2></div></div><table class="table"><caption>Final HTTP outcomes of authenticated requests</caption><thead><tr><th>Reason</th><th class="num">Requests</th><th class="num">People</th></tr></thead><tbody>${d.failures.map(f => `<tr><td>${e(statusLabels[f.status] || 'Other failure')}<small>HTTP ${e(f.status ?? 'unknown')}</small></td><td class="num">${num(f.attempts)}</td><td class="num">${num(f.users)}</td></tr>`).join('') || emptyRow(3, c.attempts ? 'No failed requests in this period.' : 'No requests to evaluate yet.')}</tbody></table><p class="analytics-footnote">People can appear in multiple reasons. Invalid API keys and unauthenticated traffic are excluded.</p></section>
  <section class="analytics-panel" id="economics"><div class="section-heading"><div><p class="analytics-eyebrow">Business health</p><h2>Will people pay for the value?</h2></div></div><dl class="economics"><div><dt>Purchased credit <small>${change(m.purchased, m.previous_purchased)}</small></dt><dd>${usd(m.purchased)}</dd></div><div><dt>Buyers <small>${num(m.first_buyers)} first-time · ${num(m.buyers - m.first_buyers)} returning buyers</small></dt><dd>${num(m.buyers)}</dd></div><div><dt>Average purchase <small>${num(m.purchases)} purchases</small></dt><dd>${m.purchases ? usd(m.purchased / m.purchases) : '—'}</dd></div><div><dt>Active users who have paid <small>${num(m.active_payers)} / ${num(c.active)} active; lifetime purchase by period end</small></dt><dd>${percent(m.active_payers, c.active)}</dd></div><div><dt>Credit consumed <small>Includes usage funded by free credit</small></dt><dd>${usd(m.consumed)}</dd></div><div><dt>Welcome / manual credit granted</dt><dd>${usd(m.granted)}</dd></div></dl><p class="analytics-footnote">Purchased credit excludes welcome grants, Stripe test checkouts, and Apple sandbox purchases. Face value before refunds, taxes, platform fees, and provider costs; this is not net revenue, profit, or MRR. Usage may be charged even when a result fails formatting.</p></section></div>

  <div class="analytics-columns"><section class="analytics-panel"><div class="section-heading"><div><p class="analytics-eyebrow">Entry points</p><h2>Where usage comes from</h2></div></div><table class="table"><thead><tr><th>Credential type</th><th class="num">Active</th><th class="num">Runs</th><th class="num">Success</th></tr></thead><tbody>${d.sources.map(s => `<tr><td>${e(sourceNames[s.source] || s.source)}</td><td class="num">${num(s.users)}</td><td class="num">${num(s.runs)}</td><td class="num">${percent(s.runs, s.attempts)}</td></tr>`).join('') || emptyRow(4, 'Source breakdown appears after the first run.')}</tbody></table><p class="analytics-footnote">Derived from the key used, not device detection. People may appear in multiple entry points.</p></section>
  <section class="analytics-panel analytics-today"><p class="analytics-eyebrow">Today · partial UTC day</p><h2>Is activity coming in?</h2><strong>${num(d.today.runs)}</strong><p>completed runs · ${num(d.today.active)} active users · ${num(d.today.attempts - d.today.runs)} failures</p><p class="analytics-footnote">${d.today.last_event ? `Last request ${new Date(d.today.last_event).toISOString().replace('T', ' ').slice(0, 19)} UTC.` : 'No authenticated requests recorded today.'} Today is excluded from the period metrics above. Updated on page load; use Refresh for the latest snapshot.</p></section></div>
  <details class="analytics-panel analytics-methodology"><summary>Metric definitions, limitations & measurement plan</summary><p>The primary signal is weekly repeat users: people receiving a successful result on at least two distinct UTC days in the last seven complete days. It combines useful reach with returning behavior. Pair growth here with activation, retention, reliability, and willingness to pay.</p><p>Selected-period counts are exact observed authenticated requests across Shortcuts, app keys, and the custom APIs. Signup counts come from account creation timestamps; repeated logins do not create signups. Install-page visits are setup attempts, not confirmed installations. Historical ledger rows cannot reconstruct completed runs, so we do not backfill them as usage.</p><p>All current accounts, including operators and test users, are included in engagement; deleted accounts are excluded from identifiable activity. Analytics writes are best-effort and are logged if they fail. Purchased credit is recorded independently in the financial ledger.</p><p>Next measurement gaps: visitor-to-signup acquisition, confirmed installation, output satisfaction, downstream task completion, and provider cost per usable result. These need additional instrumentation; they are intentionally not presented as measured KPIs.</p></details>
</div>` });
}
