import { costMicros } from './inference.js';

// Each automation is a Shortcut the user builds from the listed actions.
// Steps use the real action names from the iOS Shortcuts app.
const callApi = (extra = '') => ({
  action: 'Get Contents of URL',
  detail: `POST {{API_URL}} · Header Authorization: Bearer YOUR_KEY · JSON body: prompt${extra}`,
});

export const CATEGORIES = ['Writing', 'Productivity', 'Capture', 'Everyday'];

export const AUTOMATIONS = [
  {
    slug: 'summarize-anything',
    icon: 'doc',
    color: 'orange',
    name: 'Summarize Anything',
    tagline: 'Share any article, email or note and get a three-line summary.',
    category: 'Productivity',
    trigger: 'Share Sheet',
    model: '@cf/meta/llama-3.1-8b-instruct-fp8-fast',
    typicalTokens: [900, 120],
    prompt: 'Summarize the input in three short lines. Lead with the single most important point.',
    steps: [
      { action: 'Receive Text, Articles, URLs from Share Sheet', detail: 'Turn on "Show in Share Sheet" in the shortcut details.' },
      { action: 'Get Text from Input', detail: 'Converts shared articles and pages to plain text.' },
      callApi(', input = Text'),
      { action: 'Get Dictionary Value', detail: 'Key: text' },
      { action: 'Quick Look', detail: 'Or Show Result.' },
    ],
  },
  {
    slug: 'reply-drafter',
    icon: 'chat',
    color: 'violet',
    name: 'Reply Drafter',
    tagline: 'Copy a message, run it, and get a warm, concise reply on your clipboard.',
    category: 'Writing',
    trigger: 'Back Tap or Action Button',
    model: '@cf/meta/llama-3.3-70b-instruct-fp8-fast',
    typicalTokens: [300, 150],
    prompt: 'Draft a friendly, concise reply to this message. Match its tone. Output only the reply.',
    steps: [
      { action: 'Get Clipboard' },
      callApi(', input = Clipboard'),
      { action: 'Get Dictionary Value', detail: 'Key: text' },
      { action: 'Copy to Clipboard' },
      { action: 'Show Notification', detail: 'Reply copied.' },
    ],
  },
  {
    slug: 'tone-shifter',
    icon: 'wand',
    color: 'indigo',
    name: 'Tone Shifter',
    tagline: 'Rewrite selected text as friendlier, firmer, or more formal.',
    category: 'Writing',
    trigger: 'Share Sheet',
    model: '@cf/meta/llama-3.1-8b-instruct-fp8-fast',
    typicalTokens: [250, 120],
    prompt: 'Rewrite the input in a {{Chosen Item}} tone. Keep the meaning. Output only the rewrite.',
    steps: [
      { action: 'Receive Text from Share Sheet' },
      { action: 'Choose from Menu', detail: 'Friendlier / Firmer / More formal / Shorter' },
      callApi(' (with the chosen tone), input = Shortcut Input'),
      { action: 'Get Dictionary Value', detail: 'Key: text' },
      { action: 'Copy to Clipboard' },
    ],
  },
  {
    slug: 'voice-to-notes',
    icon: 'mic',
    color: 'green',
    name: 'Voice to Notes',
    tagline: 'Talk for a minute. Get a tidy note with action items in Apple Notes.',
    category: 'Capture',
    trigger: 'Action Button or Siri',
    model: '@cf/meta/llama-3.3-70b-instruct-fp8-fast',
    typicalTokens: [500, 250],
    prompt: 'Turn this dictation into a clean note: a title line, a short summary, then a checklist of action items.',
    steps: [
      { action: 'Dictate Text', detail: 'Stop Listening: After Pause' },
      callApi(', input = Dictated Text'),
      { action: 'Get Dictionary Value', detail: 'Key: text' },
      { action: 'Create Note', detail: 'Folder: Inbox' },
    ],
  },
  {
    slug: 'smart-reminders',
    icon: 'bell',
    color: 'yellow',
    name: 'Smart Reminders',
    tagline: 'Paste a messy list or email and get real reminders with due dates.',
    category: 'Productivity',
    trigger: 'Share Sheet',
    model: '@cf/meta/llama-3.3-70b-instruct-fp8-fast',
    typicalTokens: [400, 150],
    prompt: 'Extract tasks from the input. Return one task per line as: task | due date in ISO 8601 or blank. No other text.',
    steps: [
      { action: 'Receive Text from Share Sheet' },
      callApi(', input = Shortcut Input'),
      { action: 'Get Dictionary Value', detail: 'Key: text' },
      { action: 'Split Text', detail: 'By New Lines' },
      { action: 'Repeat with Each', detail: 'Split Text by "|", then Add New Reminder with title and due date.' },
    ],
  },
  {
    slug: 'receipt-reader',
    icon: 'receipt',
    color: 'pink',
    name: 'Receipt Reader',
    tagline: 'Scan a receipt and log merchant, date and total to a spreadsheet row.',
    category: 'Capture',
    trigger: 'Home Screen',
    model: '@cf/meta/llama-3.1-8b-instruct-fp8-fast',
    typicalTokens: [300, 40],
    prompt: 'From this receipt text, output one CSV line: merchant,date (YYYY-MM-DD),total. No header.',
    steps: [
      { action: 'Take Photo' },
      { action: 'Extract Text from Image', detail: 'Runs on device.' },
      callApi(', input = Text from Image'),
      { action: 'Get Dictionary Value', detail: 'Key: text' },
      { action: 'Append to Text File', detail: 'iCloud Drive/Receipts.csv' },
    ],
  },
  {
    slug: 'translate-selection',
    icon: 'globe',
    color: 'sky',
    name: 'Translate Selection',
    tagline: 'Natural translation that keeps names, tone and formatting intact.',
    category: 'Everyday',
    trigger: 'Share Sheet',
    model: '@cf/meta/llama-3.1-8b-instruct-fp8-fast',
    typicalTokens: [300, 300],
    prompt: 'Translate the input to {{Language}}. Keep names and formatting. Output only the translation.',
    steps: [
      { action: 'Receive Text from Share Sheet' },
      { action: 'Choose from List', detail: 'Your usual languages' },
      callApi(' (with the language), input = Shortcut Input'),
      { action: 'Get Dictionary Value', detail: 'Key: text' },
      { action: 'Show Result' },
    ],
  },
  {
    slug: 'morning-brief',
    icon: 'sun',
    color: 'amber',
    name: 'Morning Brief',
    tagline: 'A two-paragraph plan for your day from your calendar and reminders.',
    category: 'Everyday',
    trigger: 'Personal Automation at 7:00',
    model: '@cf/mistralai/mistral-small-3.1-24b-instruct',
    typicalTokens: [700, 350],
    prompt: 'Here are my events and reminders for today. Write a calm two-paragraph plan for the day, flagging conflicts.',
    steps: [
      { action: 'Find Calendar Events', detail: 'Start Date is Today' },
      { action: 'Find Reminders', detail: 'Due Date is Today, Is Not Completed' },
      { action: 'Text', detail: 'Combine both lists.' },
      callApi(', input = Text'),
      { action: 'Get Dictionary Value', detail: 'Key: text' },
      { action: 'Speak Text', detail: 'Or Show Notification.' },
    ],
  },
];

// Typical cost in USD at current prices and markup, for display.
for (const a of AUTOMATIONS) a.typicalCost = costMicros(a.model, ...a.typicalTokens) / 1e6;

export const findAutomation = (slug) => AUTOMATIONS.find((a) => a.slug === slug);
